#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Jul 20 01:55:42 2021

@author: apple
"""

N=int(input("How many sticks in the pile?"))
print('There are ',N,"sticks in the pile.")
Name=str(input('What is your name?'))
print('For each time you just can pick 1 or 2 sticks from the pile.')
X=int(input('How many sticks you will take (1 or 2)?'))
import random
if N==X:
    print('ganme over and I,smart computer win!!!')
else:
    while N != X:
         if N > X:
               N -= X
               print('There are', N, 'sticks in the pile.')
               num=random.randint(1, 2)
               print('I, smart computer takes', num)
               N -= num
               print('There are ', N, 'sticks in the pile.')
               X = int(input('How many sticks you will take (1 or 2)?'))
               num = random.randint(1, 2)
               if N-X==1:
                 print(Name,'is win (I,smart computer, am sad T_T)')
               else: 
                 N-num==1
                 print('I , samrt computer, win!!!')
               break 
    ''                 